### ISSUE TITLE
Lag spikes and missing textures with William Wythers' Expanded Ecosphere

### ISSUE THREAD

**Issue by avusfisch** [kallmetony/AntiqueAtlasReborn#3]
**Describe the bug**
Lag spikes and missing textures with William Wythers' Expanded Ecosphere. 

**Screenshots**
![grafik](https://github.com/kallmetony/AntiqueAtlasReborn/assets/78373837/32b79594-b181-444c-a4e1-d5ef9509adef)

![grafik](https://github.com/kallmetony/AntiqueAtlasReborn/assets/78373837/b5dc6a0c-68b7-499f-a320-2f0b942527b6)

**Version information (please complete the following information):**
Fabric

**Comment by avusfisch** [comment]
The /config/antiqueatlas Folder also doesn't seam to generate

**Comment by Thefatsparrow** [comment]
same with terralith though i didnt find any lag spikes

**Comment by kallmetony** [comment]
@avusfisch and @Thefatsparrow can you send me logs?
